-- 已落库的旧中文 config_name/description 可执行本脚本改为与 key 一致的英文说明（可选）
UPDATE system_config SET config_name = 'portal.frontend.api-public-origin', description = 'Browser origin for this app /api only (optional). Empty = relative /api. VITE_API_PUBLIC_ORIGIN overrides when set.' WHERE config_key = 'portal.frontend.api-public-origin';
UPDATE system_config SET config_name = 'auth.oauth.linuxdo.platform-base-url', description = 'LINUX DO Connect OAuth 2.0 base. Default https://connect.linux.do. Paths: /oauth2/authorize, /oauth2/token, /api/user' WHERE config_key = 'auth.oauth.linuxdo.platform-base-url';
UPDATE system_config SET config_name = 'auth.oauth.github.oauth-web-base-url', description = 'github.com OAuth web: /login/oauth/authorize, /login/oauth/access_token. Default https://github.com' WHERE config_key = 'auth.oauth.github.oauth-web-base-url';
UPDATE system_config SET config_name = 'auth.oauth.github.rest-api-base-url', description = 'GitHub REST API: /user, /user/emails. Default https://api.github.com' WHERE config_key = 'auth.oauth.github.rest-api-base-url';
UPDATE system_config SET config_name = 'auth.oauth.google.accounts-base-url', description = 'Google OAuth 2.0 authorization host. Default https://accounts.google.com. Path: /o/oauth2/v2/auth' WHERE config_key = 'auth.oauth.google.accounts-base-url';
UPDATE system_config SET config_name = 'auth.oauth.google.token-base-url', description = 'Google token endpoint host. Default https://oauth2.googleapis.com. Path: /token' WHERE config_key = 'auth.oauth.google.token-base-url';
UPDATE system_config SET config_name = 'auth.oauth.google.userinfo-base-url', description = 'Google OIDC userinfo host. Default https://openidconnect.googleapis.com. Path: /v1/userinfo' WHERE config_key = 'auth.oauth.google.userinfo-base-url';
UPDATE system_config SET config_name = 'auth.oauth.wechat.open-platform-base-url', description = 'WeChat Open Platform (website QR): open.weixin.qq.com. Path: /connect/qrconnect' WHERE config_key = 'auth.oauth.wechat.open-platform-base-url';
UPDATE system_config SET config_name = 'auth.oauth.wechat.sns-api-base-url', description = 'WeChat SNS API host api.weixin.qq.com. Paths: /sns/oauth2/access_token, /sns/userinfo' WHERE config_key = 'auth.oauth.wechat.sns-api-base-url';
UPDATE system_config SET config_name = 'auth.oauth.qq.open-api-base-url', description = 'QQ Connect graph host. Default https://graph.qq.com. OAuth2.0 /oauth2.0/* and /user/get_user_info' WHERE config_key = 'auth.oauth.qq.open-api-base-url';
UPDATE system_config SET config_name = 'auth.oauth.zevost.platform-base-url', description = 'Zevost base URL (doc connect.php). Default https://u.zevost.com. Appended path: /connect.php?act=login|callback' WHERE config_key = 'auth.oauth.zevost.platform-base-url';
